import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface QuotationShop {
  name: string
  address?: string | null
  whatsapp?: string | null
}

interface QuotationItem {
  name: string
  description?: string | null
  price: number
  quantity: number
  subtotal: number
}

interface QuotationData {
  id: string
  customer_name: string
  customer_phone: string
  items: QuotationItem[]
  total_amount: number
  valid_until?: string | null
  notes?: string | null
  created_at: string
}

function formatCurrency(amount: number): string {
  return `₹${amount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })
}

export function generateQuotationPDF(shop: QuotationShop, quotation: QuotationData): Buffer {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const orange = [255, 107, 0] as [number, number, number]
  const darkGray = [30, 30, 30] as [number, number, number]
  const lightGray = [200, 200, 200] as [number, number, number]

  // Header
  doc.setFillColor(...orange)
  doc.rect(0, 0, 210, 40, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(255, 255, 255)
  doc.text(shop.name, 14, 18)

  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text('QUOTATION', 196, 18, { align: 'right' })

  // Shop details
  doc.setTextColor(...darkGray)
  doc.setFontSize(9)
  let y = 50

  if (shop.address) doc.text(shop.address, 14, y), (y += 5)
  if (shop.whatsapp) doc.text(`WhatsApp: ${shop.whatsapp}`, 14, y), (y += 5)

  // Quote info (right)
  const rightX = 140
  doc.setFont('helvetica', 'bold')
  doc.text('Quote ID:', rightX, 50)
  doc.setFont('helvetica', 'normal')
  doc.text(`#${quotation.id.substring(0, 8).toUpperCase()}`, 196, 50, { align: 'right' })

  doc.setFont('helvetica', 'bold')
  doc.text('Date:', rightX, 56)
  doc.setFont('helvetica', 'normal')
  doc.text(formatDate(quotation.created_at), 196, 56, { align: 'right' })

  if (quotation.valid_until) {
    doc.setFont('helvetica', 'bold')
    doc.text('Valid Until:', rightX, 62)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(200, 80, 0)
    doc.text(formatDate(quotation.valid_until), 196, 62, { align: 'right' })
    doc.setTextColor(...darkGray)
  }

  // Divider
  y = 72
  doc.setDrawColor(...lightGray)
  doc.line(14, y, 196, y)
  y += 8

  // Customer
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('Prepared For:', 14, y)
  y += 6

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(quotation.customer_name, 14, y)
  y += 5
  doc.text(quotation.customer_phone, 14, y)
  y += 10

  // Items table
  autoTable(doc, {
    startY: y,
    head: [['#', 'Item', 'Description', 'Price', 'Qty', 'Subtotal']],
    body: quotation.items.map((item, idx) => [
      idx + 1,
      item.name,
      item.description ?? '',
      formatCurrency(item.price),
      item.quantity,
      formatCurrency(item.subtotal),
    ]),
    headStyles: {
      fillColor: orange,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 10 },
      3: { halign: 'right' },
      4: { halign: 'center', cellWidth: 12 },
      5: { halign: 'right', cellWidth: 28 },
    },
    margin: { left: 14, right: 14 },
  })

  const tableY = (doc as any).lastAutoTable.finalY + 8

  // Total box
  doc.setFillColor(255, 245, 235)
  doc.rect(130, tableY, 66, 16, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('Total Estimate:', 134, tableY + 6)
  doc.setTextColor(...orange)
  doc.text(formatCurrency(quotation.total_amount), 192, tableY + 6, { align: 'right' })
  doc.setTextColor(...darkGray)

  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.text('*This is an estimate. Final price may vary.', 134, tableY + 13)

  // Notes
  if (quotation.notes) {
    const notesY = tableY + 26
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.text('Terms & Notes:', 14, notesY)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    const noteLines = doc.splitTextToSize(quotation.notes, 100)
    doc.text(noteLines, 14, notesY + 5)
  }

  // Footer
  const pageHeight = doc.internal.pageSize.height
  doc.setDrawColor(...lightGray)
  doc.line(14, pageHeight - 20, 196, pageHeight - 20)
  doc.setFontSize(7)
  doc.setTextColor(150, 150, 150)
  doc.text(
    `To place order, contact us on WhatsApp: ${shop.whatsapp ?? ''}`,
    105,
    pageHeight - 13,
    { align: 'center' }
  )
  doc.text('Generated by GanpatiBappa Platform', 105, pageHeight - 8, { align: 'center' })

  return Buffer.from(doc.output('arraybuffer'))
}
